openapi: 3.0.0
info:
  title: admin.airport
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/public/airports:
    get:
      summary: Paged airports
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  totalCount:
                    type: number
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - code
                        - name
                        - tags
                        - translate
                      properties:
                        id:
                          type: number
                        code:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                        tags:
                          type: string
                          minLength: 1
                        location:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                              minLength: 1
                          required:
                            - id
                            - name
                        country:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                              minLength: 1
                          required:
                            - id
                            - name
                        translate:
                          type: string
                          minLength: 1
                required:
                  - totalCount
                  - data
              examples:
                example-1:
                  value:
                    totalCount: 2
                    data:
                      - id: 24
                        code: PKX
                        name: BEIJING DAXING
                        tags: 'BEIJING, Pekin'
                        location:
                          id: 24
                          name: Beijing
                        country:
                          id: 3
                          name: China
                        translate: (ru) Пекин
                      - id: 1309
                        code: LRR
                        name: Lar
                        tags: 'Лар,Лар,拉尔,Lar'
                        location:
                          id: 1309
                          name: Lar
                        country:
                          id: 21
                          name: Iran
                        translate: (ru) Лар
            application/xml:
              schema:
                description: ''
                type: object
                properties:
                  totalCount:
                    type: number
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - code
                        - name
                        - tags
                        - translate
                      properties:
                        id:
                          type: number
                        code:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                        tags:
                          type: string
                          minLength: 1
                        location:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                              minLength: 1
                          required:
                            - id
                            - name
                        country:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                              minLength: 1
                          required:
                            - id
                            - name
                        translate:
                          type: string
                          minLength: 1
                required:
                  - totalCount
                  - data
              examples:
                example-1:
                  value: '[object Object]'
      operationId: get-api-v1-public-airports?page=1&size=10&letter=B&sort=name
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: '1'
        - schema:
            type: string
          in: query
          name: letter
          description: A
        - schema:
            type: string
          in: query
          name: sort
          description: name
    parameters: []
    post:
      summary: Create airport
      operationId: post-api-v1-public-airports
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: number
                  code:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  tags:
                    type: string
                    minLength: 1
                  location:
                    type: object
                    properties:
                      id:
                        type: number
                    required:
                      - id
                  translate:
                    type: string
                    minLength: 1
                required:
                  - id
                  - code
                  - name
                  - tags
                  - location
                  - translate
              examples:
                example-1:
                  value:
                    id: 1999951
                    code: BQTA
                    name: BrestA
                    tags: 'Ballarat,Брест,Брест,Brest'
                    location:
                      id: 1650
                    translate: (ru) Брест
            application/xml:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                code:
                  type: string
                  minLength: 1
                name:
                  type: string
                  minLength: 1
                tags:
                  type: array
                  items:
                    required: []
                    properties: {}
                location:
                  type: object
                  properties:
                    id:
                      type: number
                  required:
                    - id
                translate:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                      - language
                      - name
                    properties:
                      language:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
              required:
                - code
                - name
                - tags
                - location
                - translate
            examples:
              example-1:
                value:
                  code: BQTA
                  name: BrestA
                  tags:
                    - Ballarat
                    - Брест
                    - Брест
                    - Brest
                  location:
                    id: 1650
                  translate:
                    - language: ru
                      name: Брест
          application/xml:
            schema:
              description: ''
              type: object
              properties:
                code:
                  type: string
                  minLength: 1
                name:
                  type: string
                  minLength: 1
                tags:
                  type: array
                  items:
                    required: []
                    properties: {}
                location:
                  type: object
                  properties:
                    id:
                      type: number
                  required:
                    - id
                translate:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                      - language
                      - name
                    properties:
                      language:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
              required:
                - code
                - name
                - tags
                - location
                - translate
            examples:
              example-1:
                value: '[object Object]'
        description: ''
  /api/v1/public/airports/search:
    get:
      summary: search
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - code
                    - name
                    - tags
                    - location
                    - country
                    - translate
                  properties:
                    id:
                      type: number
                    code:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    tags:
                      type: string
                      minLength: 1
                    location:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - name
                    country:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - name
                    translate:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - id: 9
                      code: NQZ
                      name: Nursultan Nazarbayev Airport
                      tags: 'Нурсултан '
                      location:
                        id: 9
                        name: Nur-Sultan (Astana)
                      country:
                        id: 1
                        name: Kazakhstan
                      translate: Аэропорт имени Нурсултан Назарбаев
      operationId: get-api-v1-public-airports-search
      parameters:
        - schema:
            type: string
          in: query
          name: pattern
          description: nur
  /api/v1/public/airports/all:
    get:
      summary: get all
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - code
                    - name
                    - tags
                    - location
                    - country
                    - translate
                  properties:
                    id:
                      type: number
                    code:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    tags:
                      type: string
                      minLength: 1
                    location:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - name
                    country:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - name
                    translate:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - id: 1999951
                      code: BQTA
                      name: BrestA
                      tags: 'Ballarat,Брест,Брест,Brest'
                      location:
                        id: 1650
                        name: Okha
                      country:
                        id: 2
                        name: Russia
                      translate: (ru) Брест
                    - id: 1309
                      code: LRR
                      name: Lar
                      tags: 'Лар,Лар,拉尔,Lar'
                      location:
                        id: 1309
                        name: Lar
                      country:
                        id: 21
                        name: Iran
                      translate: (ru) Лар
      operationId: get-api-v1-public-airports-all
  '/api/v1/public/airports/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: '1309'
    get:
      summary: get by id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: number
                  code:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  tags:
                    type: string
                    minLength: 1
                  location:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string
                        minLength: 1
                    required:
                      - id
                      - name
                  country:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string
                        minLength: 1
                    required:
                      - id
                      - name
                  translate:
                    type: string
                    minLength: 1
                required:
                  - id
                  - code
                  - name
                  - tags
                  - location
                  - country
                  - translate
              examples:
                example-1:
                  value:
                    id: 1309
                    code: LRR
                    name: Lar
                    tags: 'Лар,Лар,拉尔,Lar'
                    location:
                      id: 1309
                      name: Lar
                    country:
                      id: 21
                      name: Iran
                    translate: (ru) Лар
      operationId: get-api-v1-public-airports-id
components:
  schemas:
    Airport:
      description: ''
      type: object
      properties:
        id:
          type: number
        code:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        tags:
          type: string
          minLength: 1
        location:
          type: object
          properties:
            id:
              type: number
            name:
              type: string
              minLength: 1
          required:
            - id
            - name
        country:
          type: object
          properties:
            id:
              type: number
            name:
              type: string
              minLength: 1
          required:
            - id
            - name
        translate:
          type: string
          minLength: 1
      required:
        - id
        - code
        - name
        - tags
        - location
        - country
        - translate
      x-examples:
        example-1:
          id: 1999951
          code: BQTA
          name: BrestA
          tags: 'Ballarat,Брест,Брест,Brest'
          location:
            id: 1650
            name: Okha
          country:
            id: 2
            name: Russia
          translate: (en) Brest
