openapi: 3.0.0
info:
  title: country
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/public/countries:
    get:
      summary: paged countries
      tags: []
      responses: {}
      operationId: get-api-v1-countries
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: '1'
        - schema:
            type: integer
          in: query
          name: size
          description: '1'
        - schema:
            type: string
          in: query
          name: letter
          description: A
        - schema:
            type: string
          in: query
          name: sort
          description: name
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                totalCount:
                  type: number
                data:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                      - id
                      - name
                      - code
                      - withCitizenship
                      - tags
                      - currencyName
                      - currencyCode
                      - currencyNameInt
                      - currencyCodeInt
                      - translate
                      - cities
                    properties:
                      id:
                        type: number
                      name:
                        type: string
                        minLength: 1
                      code:
                        type: string
                        minLength: 1
                      withCitizenship:
                        type: boolean
                      tags:
                        type: string
                        minLength: 1
                      currencyName:
                        type: string
                        minLength: 1
                      currencyCode:
                        type: string
                        minLength: 1
                      currencyNameInt:
                        type: string
                        minLength: 1
                      currencyCodeInt:
                        type: string
                        minLength: 1
                      translate:
                        type: string
                        minLength: 1
                      cities:
                        type: string
                        minLength: 1
              required:
                - totalCount
                - data
            examples:
              example-1:
                value:
                  totalCount: 223
                  data:
                    - id: 3
                      name: China
                      code: CN
                      withCitizenship: true
                      tags: 'China,Kiina,Chine,Kína,中華人民共和国,Қытай,Kinija,China,Chiny,Китай,Çin,中国,الصين,Ķīna,China,Kitajska,中國'
                      currencyName: yuan
                      currencyCode: CN
                      currencyNameInt: yuan
                      currencyCodeInt: CN
                      translate: (ru) Китай
                      cities: 'Lhasa/Lasa, Lianyungang, Lijiang, Linyi, Suzhou, Tacheng, Taiyuan, Taizhou, Aksu, Bayannur, Beihai, Tianjin, Tongren, Yuncheng, Beijing, Shanghai, Urumqi, Guangzhou, Chengdu, Hangzhou, Kunming, Shenzhen, Xiamen, Altay, Anshan, Baishan, Baotou, Changchun, Changde, Changsha, Changzhou, Chongqing, Dali, Dalian, Daqing, Dunhuang, Fuyang, Fuzhou, Ganzhou, Guilin, Guiyang, Haikou, Hailar, Handan, Hanzhong, Harbin, Hefei, Heihe, Hohhot, Huai''an, Huaihua, Huangshan, Ji''an, Jiamusi, Jiayuguan, Jinan, Jingdezhen, Jinghong, Jining, Jiuzhaigou, Kashi, Lanzhou, Luoyang, Luzhou, Mangshi, Manzhouli, Meixian, Mianyang, Mudanjiang, Nanchang, Nanjing, Nanning, Nantong, Nanyang, Ningbo, Ordos, Quanzhou, Qingdao, Qiqihar, Shantou, Sanya, Shenyang, Shijiazhuang, Ulanhot, Weifang, Weihai, Wenzhou, Wuhan, Wuxi, Wuyishan, Xi An, Xiangyang, Xilinhot, Xining, Xinyuan, Xuzhou, Yancheng, Yanji, Yantai, Yibin, Yichang, Yinchuan, Yining, Yiwu, Zhangjiajie, Zhanjiang, Zhengzhou, Zhoushan, Zhuhai'
    parameters: []
  /api/v1/countries:
    post:
      summary: ''
      operationId: post-api-v1-countries
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                    minLength: 1
                  code:
                    type: string
                    minLength: 1
                  withCitizenship:
                    type: boolean
                  tags:
                    type: string
                    minLength: 1
                  currencyName:
                    type: string
                    minLength: 1
                  currencyCode:
                    type: string
                    minLength: 1
                  currencyNameInt:
                    type: string
                    minLength: 1
                  currencyCodeInt:
                    type: string
                    minLength: 1
                  translate:
                    type: string
                    minLength: 1
                required:
                  - id
                  - name
                  - code
                  - withCitizenship
                  - tags
                  - currencyName
                  - currencyCode
                  - currencyNameInt
                  - currencyCodeInt
                  - translate
              examples:
                example-1:
                  value:
                    id: 2000001
                    name: Chinah
                    code: CN
                    withCitizenship: true
                    tags: 'China,Kiina,Chine,Kína'
                    currencyName: Yuah
                    currencyCode: CNY
                    currencyNameInt: Yuah
                    currencyCodeInt: Yuah
                    translate: (en) China
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                code:
                  type: string
                  minLength: 1
                withCitizenship:
                  type: boolean
                tags:
                  type: array
                  items:
                    required: []
                    properties: {}
                translate:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                      - language
                      - name
                    properties:
                      language:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
                currencyName:
                  type: string
                  minLength: 1
                currencyCode:
                  type: string
                  minLength: 1
                currencyNameInt:
                  type: string
                  minLength: 1
                currencyCodeInt:
                  type: string
                  minLength: 1
              required:
                - name
                - code
                - withCitizenship
                - tags
                - translate
                - currencyName
                - currencyCode
                - currencyNameInt
                - currencyCodeInt
            examples:
              example-1:
                value:
                  name: Chinah
                  code: CN
                  withCitizenship: true
                  tags:
                    - China
                    - Kiina
                    - Chine
                    - Kína
                  translate:
                    - language: en
                      name: China
                  currencyName: Yuah
                  currencyCode: CNY
                  currencyNameInt: Yuah
                  currencyCodeInt: Yuah
          application/xml:
            schema:
              type: object
              properties: {}
components:
  schemas:
    country:
      description: ''
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        code:
          type: string
          minLength: 1
        withCitizenship:
          type: boolean
        tags:
          type: string
          minLength: 1
        currencyName:
          type: string
          minLength: 1
        currencyCode:
          type: string
          minLength: 1
        currencyNameInt:
          type: string
          minLength: 1
        currencyCodeInt:
          type: string
          minLength: 1
        translate:
          type: string
          minLength: 1
        cities:
          type: string
          minLength: 1
      required:
        - id
        - name
        - code
        - withCitizenship
        - tags
        - currencyName
        - currencyCode
        - currencyNameInt
        - currencyCodeInt
        - translate
        - cities
      x-examples:
        example-1:
          id: 3
          name: China
          code: CN
          withCitizenship: true
          tags: 'China,Kiina,Chine,Kína,中華人民共和国,Қытай,Kinija,China,Chiny,Китай,Çin,中国,الصين,Ķīna,China,Kitajska,中國'
          currencyName: yuan
          currencyCode: CN
          currencyNameInt: yuan
          currencyCodeInt: CN
          translate: (ru) Китай
          cities: 'Lhasa/Lasa, Lianyungang, Lijiang, Linyi, Suzhou, Tacheng, Taiyuan, Taizhou, Aksu, Bayannur, Beihai, Tianjin, Tongren, Yuncheng, Beijing, Shanghai, Urumqi, Guangzhou, Chengdu, Hangzhou, Kunming, Shenzhen, Xiamen, Altay, Anshan, Baishan, Baotou, Changchun, Changde, Changsha, Changzhou, Chongqing, Dali, Dalian, Daqing, Dunhuang, Fuyang, Fuzhou, Ganzhou, Guilin, Guiyang, Haikou, Hailar, Handan, Hanzhong, Harbin, Hefei, Heihe, Hohhot, Huai''an, Huaihua, Huangshan, Ji''an, Jiamusi, Jiayuguan, Jinan, Jingdezhen, Jinghong, Jining, Jiuzhaigou, Kashi, Lanzhou, Luoyang, Luzhou, Mangshi, Manzhouli, Meixian, Mianyang, Mudanjiang, Nanchang, Nanjing, Nanning, Nantong, Nanyang, Ningbo, Ordos, Quanzhou, Qingdao, Qiqihar, Shantou, Sanya, Shenyang, Shijiazhuang, Ulanhot, Weifang, Weihai, Wenzhou, Wuhan, Wuxi, Wuyishan, Xi An, Xiangyang, Xilinhot, Xining, Xinyuan, Xuzhou, Yancheng, Yanji, Yantai, Yibin, Yichang, Yinchuan, Yining, Yiwu, Zhangjiajie, Zhanjiang, Zhengzhou, Zhoushan, Zhuhai'
      title: country
